import type { NextPage } from "next";
import Head from "next/head";
import baseUrl from "../helpers/baseUrl";
import { categoryList } from "../types";
import { useState } from "react";
import Modal from "../component/Modal";
export interface selectType {
  id: string;
  title: string;
  photoUrL: string;
  catId: string;
}

const Home: NextPage<{
  content: Array<categoryList>;
}> = ({ content }) => {
  const [contentCategory, setContentCategory] = useState(content);
  const [click, setClick] = useState();
  const [modalShow, setModalShow] = useState(false);
  const [showModal, setShowModal] = useState(false);
  const [selectedItems, setSelectedItems] = useState([]);

  const handleSelector = (params: selectType) => {
    let Items: [] = [];
    const findElement = selectedItems.filter(
      (item) => item.catId == params.catId
    );
    if (findElement) {
      selectedItems
        .filter((item) => item.catId != params.catId)
        .map((item) => Items.push(item));
      Items.push(params);
      setSelectedItems(Items);
    } else {
      Items.push(params);
      setSelectedItems(params);
    }
  };

  return (
    <div className="bg-mycolor-backgroundColor">
      <Head>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap"
          rel="stylesheet"
        />
        <title>Take Home Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" ">
        <Modal onClose={() => setShowModal(false)} show={showModal}>
          {modalShow && (
            <div className="flex flex-row flex-wrap gap-1">
              {selectedItems.map((item: selectType) => (
                <div className=" ">
                  <img
                    className="card-img-top h-200rem w-20rem"
                    src={item.photoUrL}
                    width={100}
                    height={100}
                    alt="Card image cap"
                  />
                  <div className="w-40">
                    <p className="card-text">{item.title}</p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </Modal>
      </div>
      <h1 className="text-3xl font-bold text-center  underline text-mycolor-fontcolor hover:text-mycolor-hoverfontcolor">
        Movie Awards 2021
      </h1>
      {contentCategory.map((mainItem) => (
        <div className=" m-10">
          <div className="grid place-items-center mt-10 rounded-full bg-slate-600 w-full p-3 ">
            <h2
              className="text-center text-3xl  text-mycolor-fontcolor hover:text-mycolor-hoverfontcolor"
              key={mainItem.id}
            >
              {mainItem.title}
            </h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-5 lg:gap-3 md:gap-2 gap-1 justify-items-center mx-5 bg-mycolor-backgroundColor lg:min-h-250">
            {mainItem.items.map((item) => (
              <div className="">
                <div className="py-10">
                  <div className="rounded overflow-hidden shadow-lg max-w-sm">
                    <img
                      className="w-96 h-96"
                      src={item.photoUrL}
                      alt="Card image cap"
                    />
                    <div className="font-bold text-md mb-10  py-4 bg-mycolor-fontcolor h-20">
                      <p className="card-text text-center">{item.title}</p>
                    </div>
                    <div
                      className="item-center justify-items-center bg-green-500 hover:bg-sky-700 hover:text-mycolor-hoverfontcolor"
                      onClick={() => {
                        handleSelector({ ...item, catId: mainItem.id });
                      }}
                    >
                      <h1 className="text-3xl  text-center text-mycolor-fontcolor hover:text-mycolor-hoverfontcolor">
                        Select
                      </h1>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      ))}
      <div className="justify-center  flex align-middle pb-10">
        <div className="">
          <button
            className="bg-green-500 hover:bg-mycolor-submitbuttonbackgroundhover h-10 rounded-full "
            onClick={() => {
              setModalShow(true);
              setShowModal(true);
            }}
          >
            <h6 className="text-center text-3xl text-mycolor-fontcolor px-10">
              Submit
            </h6>
          </button>
        </div>
      </div>
    </div>
  );
};

export async function getStaticProps() {
  const res = await fetch(`${baseUrl}`);
  const data = await res.json();
  console.log("products ??", data.items);
  return {
    props: {
      content: data.items,
    },
  };
}

export default Home;
